In [ ]:
import torch

# image is a tensor on the GPU
def solve(image: torch.Tensor, width: int, height: int):
    original_shape = image.shape
    image_new = image.view(-1, 4).clone()
    image_new[:, :3] = 255 - image_new[:, :3]
    image_new = image_new.view(original_shape)
    image = image_new
    image.copy_(image_new)
    


image = torch.tensor([255, 0, 128, 255, 0, 255, 0, 255])
width = 1
height = 2

solve(image, width, height)

print(image)

tensor([255,   0, 128, 255,   0, 255,   0, 255])


In [16]:
A = torch.tensor([1, 2, 3])
B = A

In [ ]:
print(A)
print(B)

B[0] = 567

print(A)
print(B)



tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([567,   2,   3])
tensor([567,   2,   3])


In [ ]:
import torch


# input, output are tensors on the GPU
def solve(input: torch.Tensor, output: torch.Tensor, lo: float, hi: float, N: int):
    input[input <= lo] = lo
    input[input >= hi] = hi

    output.copy_(input)

    

input = torch.tensor([[1.5, -2.0, 3.0, 4.5]])
output = torch.zeros_like(input)

lo = 0.0
hi = 3.5

solve(input, output, lo, hi, 4)

print(ip)

tensor([[1.5000, 0.0000, 3.0000, 3.5000]])


In [ ]:
import torch


# A, B, output are tensors on the GPU
def solve(A: torch.Tensor, B: torch.Tensor, output: torch.Tensor, N: int):
    C = torch.stack((A, B), dim=1)
    C = torch.flatten(C)
    output.copy_(C)
  

A = torch.tensor([1.0, 2.0, 3.0])
B = torch.tensor([4.0, 5.0, 6.0])

solve(A, B, A, 5)

tensor([1., 4., 2., 5., 3., 6.])


In [ ]:
import torch


# input, output are tensors on the GPU
def solve(input: torch.Tensor, output: torch.Tensor, N: int):
    output[0] = input.sum()

input = torch.tensor([1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0])
solve(input, input, 4)

tensor(36.)
