In [ ]:
import torch


# input, output are tensors on the GPU
def solve(input: torch.Tensor, output: torch.Tensor, N: int, K: int):
    # Count elements in input tensor equal to K and store in output[0]
    print((input == K))
    output[0] = (input == K).sum()

    print(output[0])

input = torch.tensor([1, 2, 3, 4, 1])
output = torch.zeros(1)
N = 10
K = 2

solve(input, output, N, K)

tensor([False,  True, False, False, False])
tensor(1.)


In [18]:
from numpy import float32
import torch


# input, output are tensors on the GPU
def solve(input: torch.Tensor, output: torch.Tensor, N: int):
    output.copy_(torch.nn.functional.softmax(input))


ts_1 = torch.tensor([1000.0, 1.0, 2.0, 3.0], dtype=torch.float32)
solve(ts_1, ts_1, 10)

print(ts_1)



tensor([1., 0., 0., 0.])


/var/folders/0c/wc6p4cq928l53nl_01912mfm0000gn/T/ipykernel_69437/307945810.py:7: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  output.copy_(torch.nn.functional.softmax(


In [ ]:
import torch
import math


# Q, K, V, output are tensors on the GPU
def solve(
    Q: torch.Tensor, K: torch.Tensor, V: torch.Tensor, output: torch.Tensor, M: int, N: int, d: int):
    d = Q.shape[-1]
    part_1 = torch.nn.functional.softmax(Q.matmul(K.T) / math.sqrt(d))

    part_2 = part_1.matmul(V)

    output.copy_(part_2)
    

    




Q = torch.rand((2, 4))
K = torch.rand(3, 4)
V = torch.rand(3, 4)

Q = torch.tensor(
    [
        [1.0, 0, 0, 0],
        [0, 1.0, 0, 0]
    ], dtype=torch.float16
)

K = torch.tensor(
    [
        [1.0, 0, 0, 0],
        [0, 1.0, 0, 0],
        [0, 0, 1.0, 0]
    ], dtype=torch.float16
)

V = torch.tensor(
    [
        [1.0, 2.0, 3.0, 4.0],
        [5.0, 6.0, 7, 8],
        [9, 10, 11, 12]
    ], dtype=torch.float16
)

output = torch.zeros_like(V)

solve(Q, K, V, K, 1, 1, 1)


tensor([[0.4519, 0.2742, 0.2742],
        [0.2742, 0.4519, 0.2742]], dtype=torch.float16)
tensor([[4.2891, 5.2891, 6.2891, 7.2891],
        [5.0000, 6.0000, 7.0000, 8.0000]], dtype=torch.float16)


/var/folders/0c/wc6p4cq928l53nl_01912mfm0000gn/T/ipykernel_69437/3336979168.py:9: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  part_1 = torch.nn.functional.softmax(Q.matmul(K.T) / math.sqrt(d))


In [66]:
import torch


# input, kernel, output are tensors on the GPU
def solve(
    input: torch.Tensor,
    kernel: torch.Tensor,
    output: torch.Tensor,
    input_rows: int,
    input_cols: int,
    kernel_rows: int,
    kernel_cols: int,
):
    input = input.unsqueeze(0).unsqueeze(0)
    kernel = kernel.unsqueeze(0).unsqueeze(0)

    result = torch.nn.functional.conv2d(
        input, kernel, stride=1
    )

    print(result)

    output.copy_(result)


input = torch.rand((3, 3))
kernel = torch.rand((2, 2))

input = torch.tensor([1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0])
kernel = torch.tensor([0.0, 1.0, 1.0, 0.0])

solve(input, kernel, torch.tensor([1, 1]), 1, 1, 1, 1)


RuntimeError: expected stride to be a single integer value or a list of 1 values to match the convolution dimensions, but got stride=[1, 1]

In [ ]:
import torch



# data is a tensor on the GPU
def solve(data: torch.Tensor, N: int):
    data.copy_(data[torch.argsort(data)])


input = torch.rand(10, dtype=torch.float16)
print(input)

solve(input, 1)
print(input)


tensor([0.6343, 0.4365, 0.2363, 0.8862, 0.5767, 0.6240, 0.5674, 0.4707, 0.2319,
        0.9761], dtype=torch.float16)
tensor([8., 2., 1., 7., 6., 4., 5., 0., 3., 9.], dtype=torch.float16)
