In [ ]:
import torch

from torch import nn



print(input)
print(target)

tensor([[ 0.7013, -0.4100,  0.2043],
        [ 0.5977, -0.2597,  0.2574],
        [-0.1351,  1.2737,  1.6161],
        [ 0.5314,  1.7898,  1.1399],
        [-0.6916, -0.2478,  1.6746],
        [-0.8208, -1.5638,  0.5217],
        [ 0.3926,  0.3760,  1.8380],
        [ 0.6245,  0.4284,  0.1733],
        [ 0.9843, -0.4264, -0.7938],
        [-0.7152,  0.1621,  0.8370]])
tensor([[-0.0314, -0.0771,  0.3938],
        [-1.8407, -0.4461, -0.1675],
        [ 0.8235, -0.0680,  0.4158],
        [ 1.4239, -0.5138,  1.1200],
        [ 1.2817,  0.4677, -0.0502],
        [ 2.4195,  0.5297, -0.6766],
        [ 0.0286, -0.1970,  0.1403],
        [-0.1644, -0.6045,  0.0250],
        [ 1.5953, -1.3316, -0.4662],
        [ 1.6111,  0.6175, -0.2334]])


In [4]:
class LinearRegression(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1)

    def forward(self, x):
        return self.linear(x)

model = LinearRegression()


In [5]:
def loss_fn(output, target):
    return (output - target).pow(2).sum()

optimizer = torch.optim.SGD(model.parameters(), lr=0.01)
for epoch in range(100):
    optimizer.zero_grad()
    output = model(input)
    loss = loss_fn(output, target)
    loss.backward()
    optimizer.step()


In [7]:
print(target)
print(model(input))

tensor([[-0.0314, -0.0771,  0.3938],
        [-1.8407, -0.4461, -0.1675],
        [ 0.8235, -0.0680,  0.4158],
        [ 1.4239, -0.5138,  1.1200],
        [ 1.2817,  0.4677, -0.0502],
        [ 2.4195,  0.5297, -0.6766],
        [ 0.0286, -0.1970,  0.1403],
        [-0.1644, -0.6045,  0.0250],
        [ 1.5953, -1.3316, -0.4662],
        [ 1.6111,  0.6175, -0.2334]])
tensor([[-0.2225],
        [-0.1252],
        [ 0.5389],
        [ 0.2644],
        [ 0.5676],
        [ 0.5119],
        [-0.0516],
        [ 0.0226],
        [-0.2867],
        [ 0.7868]], grad_fn=<AddmmBackward0>)
